### PR TITLE
jubjub 0.7

### PR DESCRIPTION
**Pull request by str4d**

### CODE REVIEW

**Review by oxarbitrage — APPROVED** [review]
I don't see why not :)

**Comment by str4d** [comment]
This PR is necessary for ZIP 216 consensus compatibility post-NU5. It does not provide pre-NU5 consensus compatibility, but hopefully that's not something `zebrad` will need to worry about (and if it were, `zebrad` could depend on two versions).

**Comment by conradoplg** [comment]
We need this for Zebra, and I have indirectly test this already (compilation-wise) by locally pointing Zebra to use this. Any objections in merging it?

**Comment by dconnolly** [comment]
> We need this for Zebra, and I have indirectly test this already (compilation-wise) by locally pointing Zebra to use this. Any objections in merging it?

Great! I'll merge

**Review by dconnolly — APPROVED** [review]

**Pull request merged**
