### PR TITLE
Release 0.7.0

### PR DESCRIPTION
**Pull request by daira**

### CODE REVIEW

**Review by nuttycom — APPROVED** [review]
utACK

**Review by teor2345 — APPROVED** [review]
Thanks, looks great!

**Comment by teor2345** [comment]
(We don't have mergify on this repository, so feel free to manually merge when you're happy with the PR, CI & the reviews it's got.)

**Comment by daira** [comment]
> (We don't have mergify on this repository, so feel free to manually merge when you're happy with the PR, CI & the reviews it's got.)

I don't seem to have permission to merge on this repo.

**Comment by daira** [comment]
I checked the zcashd dependency graph, and there doesn't seem to be anything more we need to do to reduce duplicates as far as this crate is concerned.

**Comment by str4d** [comment]
This PR was merged with a squash commit, which means that none of the commits in the branch ended up in `main`. But the commit in this branch is the one that was tagged for release. This means that the tag does not appear in the repo's main history, which is a major problem. We need to fix this by explicitly merging the release commit into `main`, and ensuring that merge commits can be created in this repo when necessary (ECC prefers merge commits over squash commits in general, but here it would have been a requirement due to the presence of the tag).

**Pull request merged**
